server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user_service # 路由标识
          uri: lb://userservice # 路由地址
          predicates:
            - Path=/user/** # 路径断言，判断路径是否以/user开头
            - Before=2030-01-20T17:42:47.789-07:00[Asia/Shanghai] # 时间断言，判断是否在指定时间之后
          filters:
            - AddRequestHeader=Truth, Itcast is freaking awesome! # 添加请求头
        - id: order_service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
            - After=2030-01-20T17:42:47.789-07:00[Asia/Shanghai]